# Transient db - will lose it's data once restarted
version: "3"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    restart: always
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - "127.0.0.1:3307:3306"
